image: golang:1.18.0-buster

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest

stages:
  - test
  - build
  - deploy

coverage:
  stage: test
  tags:
    - gitlab-go-runners
  script:
    - go test $(go list ./... | grep -v /vendor/) -v -cover

publish:
  image: docker:latest
  stage: build
  tags:
    - gitlab-go-runners
  services:
    - docker:dind
  script:
    - docker build -t $TAG_LATEST . || build_status=$?
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_LATEST || publish_status=$?
    - docker image rm $TAG_LATEST
  only:
    refs:
      - /^main.*/

deployment:
  image: alpine:latest
  stage: deploy
  tags:
    - gitlab-go-runners
  before_script:
    - chmod og= $SSH_KEY
    - apk update && apk add openssh-client
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $GODEPLOY_SERVERIP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - ssh $GODEPLOY_SERVERUSER@$GODEPLOY_SERVERIP 
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $TAG_LATEST
    - docker service update --force devp_abenezer
  only:
    refs:
      - /^main.*/
